### ISSUE TITLE
activeadmin installs kaminari-activerecord instead of kaminari-mongoid which results in error while browsking users in admin panel

### ISSUE THREAD

**Issue by greggzst** [activeadmin/activeadmin-mongoid#110]
As written in title I don't know why but by default it downloads wrong version of this gem. Here is how I set up my environment:

`rails new test-activeadmin-mongoid --skip-active-record`

After adding mongoid I run:

```
bundle install
rails g mongoid:config
```

Then installed devise and activeadmin-mongoid. After instalation I created user as in readme and logged in but after I clicked on `AdminUsers` in activeadmin I got:
```
undefined method `page' for #<Mongoid::Criteria:0x007f6e74337680>
````

**Comment by boie0025** [comment]
Related to [NoMethodError in Admin::Users#index undefined method `associations' for User:Class](https://github.com/activeadmin/activeadmin-mongoid/issues/111)

**Comment by boie0025** [comment]
@greggzst Were you able to get around this issue now?  Is this a different project than the other issue?

**Comment by greggzst** [comment]
@boie0025 Yes, I was. No that is the same project but it would be great if `kaminari-mongoid` was added as a dependency and downloaded when `MongoDB` is used in an app.
