### ISSUE TITLE
Rails 5.1.x support

### ISSUE THREAD

**Issue by boie0025** [activeadmin/activeadmin-mongoid#112]
Add support for Rails 5.1

**Comment by grzegorz-jakubiak** [comment]
@boie0025 I'm happy to help with this if you're willing to share what needs to be done.

**Comment by boie0025** [comment]
H @grzegorz-jakubiak -- I would be very grateful for your help!  I have this slotted for Q3, so it'll be a while before I can get to it yet. 

Shouldn't be too bad; bump the Rails version in the test_app, run the specs and clean up the fallout.  I suspect there may be a mongoid upgrade that needs to be paired with it, but I don't know that for sure.  If it does wind up being too much, I'd also be very appreciative of a write up of what the upgrade will entail (for instance, which gems had to be bumped, which specs fail, etc.).

**Comment by grzegorz-jakubiak** [comment]
@boie0025 Thanks! I might be able to start working on it this weekend if not then possibly next.

**Comment by boie0025** [comment]
@grzegorz-jakubiak Very much appreciated!
