### ISSUE TITLE
In ActiveAdmin 1.2.0 NoMethodError: undefined method `inheritance_column 'for

### ISSUE THREAD

**Issue by aimerald** [activeadmin/activeadmin-mongoid#113]
Hi!
If activeadmin is set to 1.2.0 
```
NoMethodError: undefined method` inheritance_column 'for MyModel: class
```
I am  embarrassed...(´・ω・`)
Does anyone know what to fix by solving it?

**Comment by Fivell** [comment]
@aimerald what kind of model do you use? ActiveRecord or ActiveModel ?

**Comment by Fivell** [comment]
@aimerald this might help https://github.com/activeadmin/activeadmin/pull/5253#discussion_r155525109

**Comment by boie0025** [comment]
@aimerald Any luck with @Fivell's suggestion?  I haven't yet used the gem with ActiveAdmin 1.2, I intend to do so in the next week or so.

**Comment by tiagotex** [comment]
I also encountered this problem while updating from ActiveAdmin 1.1 to 1.2 and the error message was not helpful at all.

Could we support non ActiveRecord resources using @Fivell suggestion or at least have a more helpful error message?

 I'm available to implement one of the options.
