### ISSUE TITLE
Error with ransack, activeadmin-mongoid

### ISSUE THREAD

**Issue by drcenterprises** [activeadmin/activeadmin-mongoid#115]
I am having the next error, There was an error while trying to load the gem 'activeadmin-mongoid'.
Gem Load Error is: uninitialized constant ActiveRecord Backtrace for gem load error is:
/usr/local/bundle/gems/ransack-1.8.7/lib/ransack/helpers/form_builder.rb:9:in `<class:Base>'

In my application.rb I have 

require "action_controller/railtie"
require "action_mailer/railtie"
require "active_resource/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"

**Comment by jonthdiaz** [comment]
Yes i have the same problema

**Comment by bryanlo22** [comment]
Try using
`gem 'ransack', '< 1.8.7'`

**Comment by jonthdiaz** [comment]
@bryanlo22 thank you so much worked for me
