### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin-mongoid#129]
Hi,

Thanks for the great gem!

I'm following readme, trying to install the gem. As my project is fairly new, I didn't have activeadmin setup before. With that said, I also didn't have devise gem installed. That was the first failure after installing activeadmin-mongoid. The second issue now is from the readme, saying to require `"active_resource/railtie"`, while I didn't install activeresource gem neither.

I think a better approach would be to have this mentioned in the readme, instead of gem users going back and forth between missing dependencies error messaged and installing those dependencies.

EDIT: It would also make it clearer whether gems like devise and/or activeresource are required or optional.

Thanks! ❤️

**Comment by vfonic** [comment]
I'm stuck on 

```
/Users/vfonic/.gem/ruby/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activeadmin-mongoid'.
Gem Load Error is: uninitialized constant ActiveRecord
```

That points to:
```
/Users/vfonic/myapp/config/application.rb:11:in `<top (required)>'
```

Which is this line:
```rb
require_relative 'boot'

require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'active_resource/railtie'
require 'sprockets/railtie'
require 'rails/test_unit/railtie'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups) ########################################## <= THIS LINE

module Civiclift
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Don't generate system test files.
    config.generators.system_tests = nil
  end
end

```


Here's my `Gemfile`:

```rb
source 'https://rubygems.org'

ruby '2.5.1'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails'
gem 'puma'
gem 'sass-rails'
gem 'uglifier'
# gem 'bootsnap', require: false
gem 'jbuilder'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

gem 'pry-rails'
gem 'awesome_print'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'mini_racer', platforms: :ruby
gem 'rack-timeout'

gem 'pg'

gem 'figaro'

# gem 'webpacker'
# gem 'react_on_rails', '11.0.7'

gem 'activeadmin-mongoid', '~> 0.5.0'
gem 'activeresource'
gem 'devise'

gem 'http'
gem 'addressable'
gem 'rollbar'
gem 'aws-sdk-s3'
gem 'cloudinary'
```


Am I doing something wrong? How can I ensure ActiveRecord is not being loaded?

**Comment by xfynx** [comment]
@vfonic why do you need to use activeadmin-mongoid with postgres? activeadmin-mongoid is the hack to activeadmin, which helps with integration activeadmin and mongoid orm, but in your gemfile i see only `pg` and no `mongoid`

**Comment by xfynx** [comment]
@vfonic and if you just switch to plain `activeadmin` and replace back 
```
require "action_controller/railtie"
require "action_mailer/railtie"
require "active_resource/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"
```
to
`require 'rails/all'`,
you'll can fix this problem :-)

**Comment by vfonic** [comment]
Ah, you're right!

Well, I was (about to start) using ActiveRecord in my app, but then I also needed mongo and if I could make it work with ActiveAdmin, that would be magical and I'd drop pg/ActiveRecord support. I'll remove 'pg' gem and add 'mongoid' and let you know if that fixes the issue.

**Comment by xfynx** [comment]
@vfonic note that some features of activeadmin (such as built-in filters, you'll need to implement by yourself and with database indexing) not implemented here for mongoid due to features of mongodb, so if you are limited to choice between pg and mongo just in this, better pick pg and main gem for that needs

**Comment by vfonic** [comment]
Thanks @xfynx! I have some data in mongo that I need to access (and would be ideal to be able to get to that data in an ActiveAdmin-like interface).

It still doesn't work. So I took a step back, and created a new rails app:
```sh
rails _5.1.6_ new active_admin_mongoid --skip-coffee --skip-turbolinks --skip-test --skip-system-test --skip-active-record
cd active_admin_mongoid
echo "gem 'activeadmin-mongoid', '~> 0.5.0'" >> Gemfile # mongoid 6.0.3 is installed as dependency
bundle update
rails console
```

>>> /Users/vfonic/.gem/ruby/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activeadmin-mongoid'.
Gem Load Error is: uninitialized constant ActiveRecord
Did you mean?  ActiveModel

:/ Should I try with lower rails version?

**Comment by xfynx** [comment]
@vfonic 
oh, i got it.
you'll need to add `gem 'ransack', '<=1.8.6'` **after** line `gem 'activeadmin-mongoid'`.
i'll add it to readme later with PR. newer version of ransack causes your error. and probably you'll get error about devise - just add it too and app will start work.

There are still troubles around mongoid and activeadmin :-)

**Comment by vfonic** [comment]
It worked! Thanks so much @xfynx! I'll try add actually add something to AA now and will let you know whether it works for actually loading data or just the rails server starts. Then I'll close the issue.

**Comment by vfonic** [comment]
Hey @xfynx,

After some playing around, I figured I also need `gem 'kaminari-mongoid'` for the index pages.

Thanks for the help setting it all up! It works now.
