### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [activeadmin/activeadmin-mongoid#131]

**Comment by deivid-rodriguez** [comment]
I'm removing this assignment because I have enough on my plate, but ping me with any questions if you need to! :+1:

**Comment by grzegorz-jakubiak** [comment]
@deivid-rodriguez Ok thanks, it's just I don't have access to rubygems so I won't be able to release new version.

**Comment by deivid-rodriguez** [comment]
Ah, I see! I don't think I have permissions either.

Let's wait until we have a release ready to ship and then we care about releasing it :+1:

**Comment by boie0025** [comment]
Sorry for the delay, @grzegorz-jakubiak @deivid-rodriguez See PR #139
