### ISSUE TITLE
undefined method `ransack' for #<Mongoid::Criteria

### ISSUE THREAD

**Issue by shivabhusal** [activeadmin/activeadmin-mongoid#141]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/8004593/58608279-8cdbeb80-82c2-11e9-837a-153f14394295.png">

Ruby: 2.6.0
Rails: 5.2
```ruby
    activeadmin-mongoid (0.9.0)
      activeadmin (>= 1.4.3)
      jquery-rails
      kaminari-mongoid
      mongoid (~> 6.0)
      sass-rails (>= 3.1.4)
    ransack (2.1.1)
```

**Comment by xfynx** [comment]
@shivabhusal check this out: https://github.com/activeadmin/activeadmin-mongoid#some-gems
i think you need to install ransack-mongoid and it will work
