### ISSUE TITLE
Mongoid 7 support

### ISSUE THREAD

**Issue by ajsharp** [activeadmin/activeadmin-mongoid#142]
Currently using mongoid 7 and I can't install the gem bc this gem has a dependency on mongoid ~> 6.x.

**Comment by grzegorz-jakubiak** [comment]
@ajsharp hey sorry for a very late response could you try out [feture/mongoid-7](https://github.com/activeadmin/activeadmin-mongoid/tree/feature/mongoid-7) branch and let us know if this produces any errors? CI seems to pass but it'd be great if you could let us know bout any issues

**Comment by grzegorz-jakubiak** [comment]
Fixed
