### ISSUE TITLE
method_missing: undefined method `active_record'

### ISSUE THREAD

**Issue by leabdalla** [activeadmin/activeadmin-mongoid#39]
When I try to execute 

```
$ rails g devise:install
```

It returns the errors:

```
/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.11/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x007fc6cbc2b6d8> (NoMethodError)
```

Any idea?

**Comment by sajjadmurtaza49** [comment]
i am facing same problem.
--------------------application.rb
require File.expand_path('../boot', __FILE__)

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"
Bundler.require(*Rails.groups)

module Vollet
  class Application < Rails::Application

  end
end
------------------------
when am trying 
rails g devise:install

`method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x007fa637253d90> (NoMethodError)

**Comment by elia** [comment]
@sajjadmurtaza49 you need to remove all the active record related entries from `application.rb` and `config/initializers/*`

**Comment by elia** [comment]
@sajjadmurtaza49 and of course `config/environments/*` as mentioned above
