### ISSUE TITLE
Select Filter doesn't work on static valued /non Mongoid field

### ISSUE THREAD

**Issue by jigyasam** [activeadmin/activeadmin-mongoid#53]
I'm trying to add a drop down filter on a custom field with static values.

<code> filter :operation, :as => :select, :collection => ["min", "max"]</code>

Here, 'operation' is not a 'field' in my registered Mongoid model. 

I get an error with the following stack trace:
<code> 
ActionView::Template::Error (undefined method `operation_eq' for #MetaSearch::Searches::MongoidSearchBuilder:0x007f8f7be2a420):
    1: insert_tag renderer_for(:index)
</code>

I'm on latest master branch of this repo. I guess MetaSearch creates the dynamic '_eq' methods only on Mongoid fields. When I try a 'select' on a model field, it works well.  This used to work on mongoid 2.x. Any pointers on how to fix it?

**Comment by xtrasimplicity** [comment]
I had a very similar issue with a completely different gem, and ended up (after a number of hours of investigating ways to override the setter/getters) instanciating each custom field (as I was accessing the new action in the users controller, I added the following to users#new), from an array of custom fields. i.e.

 # GET /users/new
  def new
    @user = User.new

    # Instanciate all dynamic fields, just in case!
    dynamicFieldList = User.get_custom_fields

    dynamicFieldList.each do |customField|
      @user[customField] = ""
    end

  end
