### ISSUE TITLE
Dependencies problem after add gem 'activeadmin-mongoid'

### ISSUE THREAD

**Issue by cpfarher** [activeadmin/activeadmin-mongoid#98]
This is with ruby 2.1.3p242 and rails Rails 4.1.4.
I have an app with activeadmin working with activerecord and postsgresql.... I am migrating to mongo db:
- I add in gemfile gem "mongoid", "~> 4.0.0"
  and run bundle install:

Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    activeadmin-mongoid (>= 0) ruby depends on
      meta_search (~> 1.1.3) ruby depends on
        actionpack (~> 3.1) ruby

```
meta_request (>= 0) ruby depends on
  railties (< 5.0.0, >= 3.0.0) ruby depends on
    actionpack (4.1.4)
```

Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    activeadmin-mongoid (>= 0) ruby depends on
      mongoid (~> 2.0) ruby

```
mongoid (4.0.2)
```

**Comment by boie0025** [comment]
If you're on the latest ref of activeadmin-mongoid, you should be able to remove meta_request from your gemfile, try that and run your admin specs/tests.  We've removed meta_search completely from our application as it was not used elsewhere.
