### ISSUE TITLE
Support for sass-rails 5.0 dependency?

### ISSUE THREAD

**Issue by SailorMercury** [activeadmin/activeadmin-mongoid#99]
Rails : 4.2.1
Ruby : 2.2
Mongoid : 4.0.2

getting this error when trying to bundle

Bundler could not find compatible versions for gem "sass-rails":
  In snapshot (Gemfile.lock):
    sass-rails (5.0.1)

  In Gemfile:
    activeadmin-mongoid (>= 0) ruby depends on
      sass-rails (< 5.0, >= 3.1.4) ruby

**Comment by boie0025** [comment]
which ref are you using for activeadmin-mongoid?
